# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
  labels:
    tier: frontend
    app: nginx

spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 4    
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
    