# Replication Controller definition
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: my-app
    type: front-end

spec:
  template:
    metadata:
      name: nginx-custom
      labels:
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2